### ISSUE TITLE
Requires run-on-main-thread to be TRUE

### ISSUE THREAD

**Issue by designbymind** [hansemannn/ti.keyframes#1]
Hey Hans,

Awesome module & thanks for pushing a Titanium supported version!

It seems as if the app needs to be ran on the main thread in order for ti.keyframes to work properly. Is this by design? When setting the below property in **tiapp.xml**, I'm getting the following script error:
`<property name="run-on-main-thread" type="bool">false</property>`

**Error message(s):**
```
· message = "Resource was null";
· nativeLocation = "-[TiKeyframesVectorViewProxy loadSampleVectorFromDisk] (TiKeyframesVectorViewProxy.m:27)";
· nativeReason = "The specified JSON resource was null, please define it by setting the 'resource' key.";
```

Two separate apps (Classic/Alloy) were tested on both simulator/device:
· SDK 6.0.0.GA
· iOS 9.3/10

Let me know if I can provide any additional info or example code 🙂

**Comment by hansemannn** [comment]
Hey @designbymind, thanks for the report! Fixed this in the [1.0.1](https://github.com/hansemannn/ti.keyframes/releases/tag/v1.0.1) release!
